definitions:
  handlers.Dependency:
    properties:
      package_name:
        type: string
      version:
        type: string
    type: object
  handlers.HealthResponse:
    properties:
      dependencies:
        additionalProperties:
          $ref: '#/definitions/handlers.Dependency'
        type: object
      message:
        type: string
      timestamp:
        type: string
      uptime:
        type: string
      version:
        type: string
    type: object
  handlers.InfoResponse:
    properties:
      cpu_count:
        type: integer
      go_version:
        type: string
      goroutine_count:
        type: integer
      hostname:
        type: string
      os:
        type: string
      uptime:
        type: string
    type: object
  handlers.PingResponse:
    properties:
      message:
        type: string
    type: object
  handlers.VersionResponse:
    properties:
      build_commit:
        type: string
      build_date:
        type: string
      go_version:
        type: string
      version:
        type: string
    type: object
info:
  contact: {}
paths:
  /health:
    get:
      description: Returns the application health status, version, uptime, timestamp,
        and dependencies
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.HealthResponse'
      summary: Get application health status
      tags:
      - health
  /info:
    get:
      description: Returns the application Go version, uptime, hostname, OS, goroutine
        count, and CPU count
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.InfoResponse'
      summary: Get application information
      tags:
      - info
  /ping:
    get:
      description: Returns pong
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.PingResponse'
      summary: Ping endpoint
      tags:
      - health
  /version:
    get:
      description: Returns the application version, build commit, build date, and
        Go version
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.VersionResponse'
      summary: Get application version information
      tags:
      - info
swagger: "2.0"
